/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

/**
 *
 * @author marcos.fergar
 */
public class DialogoVehiculo extends javax.swing.JDialog {

    /**
     * Creates new form DialogoVehiculo
     */
    public DialogoVehiculo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public String getMatricula(){
        return this.textMATRICULA.getText();
    }
    
    public String getGrupo(){
        return (String) this.comboGrupo.getSelectedItem();
    }
    
    public int getPlazas(){
        return (Integer)this.spinnerPlazas.getValue();
    }
    
    public String getTipo(){
        return (String) this.comboTipo.getSelectedItem();
    }
    public float getCapacidad(){
        return Float.parseFloat(this.formatedCapacidad.getValue().toString());
    }    
    
    public int mostrar(){
        opcion=CANCELAR;
        this.setVisible(true);
        return opcion;
    }
    
    public void limpiarCampos() {
        this.textMATRICULA.setText("");
        this.spinnerPlazas.setValue(0);
        this.formatedCapacidad.setText("");
    }
    
    private int opcion;    
    public static final int ACEPTAR=1;
    public static final int CANCELAR=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datosVehiculo = new javax.swing.JPanel();
        labelMatricula = new javax.swing.JLabel();
        labelGrupo = new javax.swing.JLabel();
        labelPlazas = new javax.swing.JLabel();
        labelTurismo = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        comboGrupo = new javax.swing.JComboBox<>();
        comboTipo = new javax.swing.JComboBox<>();
        textMATRICULA = new javax.swing.JTextField();
        spinnerPlazas = new javax.swing.JSpinner();
        labelCapacidad = new javax.swing.JLabel();
        formatedCapacidad = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        datosVehiculo.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de vehiculo"));

        labelMatricula.setText("MATRICULA");

        labelGrupo.setText("GRUPO");

        labelPlazas.setText("PLAZAS");

        labelTurismo.setText("TIPO");

        botonAceptar.setText("ACEPTAR");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setText("CANCELAR");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        comboGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Turismo", "Furgoneta" }));
        comboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoActionPerformed(evt);
            }
        });

        labelCapacidad.setVisible(false);
        labelCapacidad.setText("Capacidad");

        formatedCapacidad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        formatedCapacidad.setValue(0.0f);
        formatedCapacidad.setVisible(false);
        formatedCapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatedCapacidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout datosVehiculoLayout = new javax.swing.GroupLayout(datosVehiculo);
        datosVehiculo.setLayout(datosVehiculoLayout);
        datosVehiculoLayout.setHorizontalGroup(
            datosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosVehiculoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(datosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datosVehiculoLayout.createSequentialGroup()
                        .addComponent(botonAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonCancelar)
                        .addGap(35, 35, 35))
                    .addGroup(datosVehiculoLayout.createSequentialGroup()
                        .addGroup(datosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(datosVehiculoLayout.createSequentialGroup()
                                .addComponent(labelMatricula)
                                .addGap(18, 18, 18)
                                .addComponent(textMATRICULA, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(datosVehiculoLayout.createSequentialGroup()
                                .addGroup(datosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(datosVehiculoLayout.createSequentialGroup()
                                        .addComponent(labelGrupo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(comboGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(datosVehiculoLayout.createSequentialGroup()
                                        .addComponent(labelPlazas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(spinnerPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(36, 36, 36)
                                .addGroup(datosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(datosVehiculoLayout.createSequentialGroup()
                                        .addComponent(labelCapacidad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(formatedCapacidad))
                                    .addGroup(datosVehiculoLayout.createSequentialGroup()
                                        .addComponent(labelTurismo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(78, Short.MAX_VALUE))))
        );
        datosVehiculoLayout.setVerticalGroup(
            datosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosVehiculoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(datosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMatricula)
                    .addComponent(textMATRICULA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(datosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGrupo)
                    .addComponent(labelTurismo)
                    .addComponent(comboGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(datosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelCapacidad)
                        .addComponent(formatedCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(datosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelPlazas)
                        .addComponent(spinnerPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(datosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar)
                    .addComponent(botonCancelar))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(datosVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(datosVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        if(!botonAceptar.getText().isBlank()){
            opcion=ACEPTAR;
            setVisible(false);
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void formatedCapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatedCapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formatedCapacidadActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed
        if(this.comboTipo.getSelectedItem()=="Turismo"){
            this.labelPlazas.setVisible(true);
            this.spinnerPlazas.setVisible(true);
            this.labelCapacidad.setVisible(false);
            this.formatedCapacidad.setVisible(false);
        }else {
            this.labelPlazas.setVisible(false);
            this.spinnerPlazas.setVisible(false);
            this.labelCapacidad.setVisible(true);
            this.formatedCapacidad.setVisible(true);
        }
    }//GEN-LAST:event_comboTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogoVehiculo dialog = new DialogoVehiculo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JComboBox<String> comboGrupo;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JPanel datosVehiculo;
    private javax.swing.JFormattedTextField formatedCapacidad;
    private javax.swing.JLabel labelCapacidad;
    private javax.swing.JLabel labelGrupo;
    private javax.swing.JLabel labelMatricula;
    private javax.swing.JLabel labelPlazas;
    private javax.swing.JLabel labelTurismo;
    private javax.swing.JSpinner spinnerPlazas;
    private javax.swing.JTextField textMATRICULA;
    // End of variables declaration//GEN-END:variables
}
