/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controlador;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import modelo.ComparadorPrecio;
import modelo.MatriculaException;
import modelo.Vehiculo;

/**
 *
 * @author alvaro.gargon.4
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }
    private DialogoVehiculo dialogoVehiculo=new DialogoVehiculo(this,true);
    private Controlador controlador;
    
    public String getMatricula(){
        return this.textFieldMatricula.getText();
    }
    
    public String getGrupo(){
        return this.comboBoxGrupo.getSelectedItem().toString();
    }
    
    public String getTipo(){
        return this.comboBoxTipo.getSelectedItem().toString();
    }
    
    public int getPlazas(){
        return (Integer)this.spinnerPlazas.getValue();
    }
    
    public float getCapacidad(){
        return Float.parseFloat(this.formattedTextFieldCapacidad.getValue().toString());
    }
    
    public String getArchivo(){
        return this.selectorFicheros.getSelectedFile().getAbsolutePath();
    }
    
    public String getOrden(){
        return this.buttonGroup1.getSelection().getActionCommand();
    }
    
    public String getFiltroGrupo(){
        return this.comboBoxFiltrarGrupo.getSelectedItem().toString();
    }
    
    public String getFiltroTipo(){
        return this.comboBoxFiltrarTipo.getSelectedItem().toString();
    }
    
    
    public void mostrarMatricula(String matricula){
        this.textFieldMatricula.setText(matricula);
    }
    
    public void mostrarTipo(String tipo){
        this.comboBoxTipo.setSelectedItem(tipo);
    }
    
    public void mostrarGrupo(String grupo){
        this.comboBoxGrupo.setSelectedItem(grupo);
    }
    
    public void mostrarPlazas(int plazas){
        this.spinnerPlazas.setValue(plazas);
    }
    
    public void mostrarCapacidad(float capacidad){
        this.formattedTextFieldCapacidad.setValue(capacidad);
    }
    
    public void mostrarPrecioAlquiler(float precio){
        this.formatedTextFieldPrecioAlquiler.setValue(precio);
    }
    
    public void listarVehiculos(List<Vehiculo> listado){
        vehiculoTM.setListadoVehiculos(listado);
    }
    
    public void limpiarCampos(){
        this.textFieldMatricula.setText("");
        this.spinnerPlazas.setValue(0);
        this.formattedTextFieldCapacidad.setText("");
        this.formatedTextFieldPrecioAlquiler.setText("");
    }
    
    public void mostrar(){
        setVisible(true);
    }
    
     public boolean solicitarConfiramcion(){
        int opcion = JOptionPane.showConfirmDialog(this, 
            "¿Está seguro que desea continuar?", "Confirmación", JOptionPane.YES_NO_OPTION);
        return opcion == JOptionPane.YES_OPTION;
    }
    
    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }
    
    public void mostrarMensaje(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectorFicheros = new javax.swing.JFileChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        panelDatos = new javax.swing.JPanel();
        labelMatricula = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botonBarato = new javax.swing.JButton();
        botonCaro = new javax.swing.JButton();
        textFieldMatricula = new javax.swing.JTextField();
        labelGrupo = new javax.swing.JLabel();
        comboBoxGrupo = new javax.swing.JComboBox<>();
        labelTipo = new javax.swing.JLabel();
        comboBoxTipo = new javax.swing.JComboBox<>();
        labelPlazas = new javax.swing.JLabel();
        spinnerPlazas = new javax.swing.JSpinner();
        labelPrecioDia = new javax.swing.JLabel();
        botonBorrar = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        labelCapacidad = new javax.swing.JLabel();
        formattedTextFieldCapacidad = new javax.swing.JFormattedTextField();
        formatedTextFieldPrecioAlquiler = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        botonListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        labelOrden = new javax.swing.JLabel();
        radioBotonMatricula = new javax.swing.JRadioButton();
        radioBotonPrecioAlquiler = new javax.swing.JRadioButton();
        labelFiltrarPorGrupo = new javax.swing.JLabel();
        labelFiltrarPorTipo = new javax.swing.JLabel();
        comboBoxFiltrarGrupo = new javax.swing.JComboBox<>();
        comboBoxFiltrarTipo = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuAbrir = new javax.swing.JMenuItem();
        menuGuardar = new javax.swing.JMenuItem();
        menuVehiculo = new javax.swing.JMenu();
        menuNuevo = new javax.swing.JMenuItem();
        menuBuscar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)), "Datos de vehiculo"));

        labelMatricula.setText("MATRÍCULA");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)), "Otras operaciones"));

        botonBarato.setText("MOSTRAR VEHICULO MÁS BARATO");
        botonBarato.setActionCommand("BARATO");
        botonBarato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBaratoActionPerformed(evt);
            }
        });

        botonCaro.setText("MOSTRAR VEHICULO MÁS CARO");
        botonCaro.setActionCommand("CARO");
        botonCaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCaroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonBarato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonCaro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(botonBarato)
                .addGap(34, 34, 34)
                .addComponent(botonCaro)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        textFieldMatricula.setEditable(false);

        labelGrupo.setText("GRUPO");

        comboBoxGrupo.setEditable(true);
        comboBoxGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));
        comboBoxGrupo.setEnabled(false);
        comboBoxGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxGrupoActionPerformed(evt);
            }
        });

        labelTipo.setText("Tipo");

        comboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TURISMO", "FURGONETA" }));
        comboBoxTipo.setEnabled(false);
        comboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTipoActionPerformed(evt);
            }
        });

        labelPlazas.setText("PLAZAS");

        labelPrecioDia.setText("PRECIO POR DÍA");

        botonBorrar.setText("BORRAR");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        botonModificar.setText("MODIFICAR");
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        labelCapacidad.setText("CAPACIDAD");
        labelCapacidad.setVisible(false);

        formattedTextFieldCapacidad.setValue(0.0f);
        formattedTextFieldCapacidad.setVisible(false);

        formatedTextFieldPrecioAlquiler.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        formatedTextFieldPrecioAlquiler.setValue(0.0f);

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(botonBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonModificar))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPrecioDia)
                            .addComponent(labelCapacidad))
                        .addGap(26, 26, 26)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(formattedTextFieldCapacidad)
                            .addComponent(formatedTextFieldPrecioAlquiler)))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDatosLayout.createSequentialGroup()
                                    .addComponent(labelPlazas)
                                    .addGap(18, 18, 18)
                                    .addComponent(spinnerPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDatosLayout.createSequentialGroup()
                                    .addComponent(labelGrupo)
                                    .addGap(18, 18, 18)
                                    .addComponent(comboBoxGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labelMatricula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldMatricula)
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(labelTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboBoxTipo, 0, 107, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMatricula)
                    .addComponent(textFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGrupo)
                    .addComponent(comboBoxGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTipo)
                    .addComponent(comboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPlazas)
                    .addComponent(spinnerPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formattedTextFieldCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrecioDia)
                    .addComponent(formatedTextFieldPrecioAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBorrar)
                    .addComponent(botonModificar))
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)), "Listado de vehículos"));

        botonListar.setText("LISTAR VEHÍCULOS");
        botonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListarActionPerformed(evt);
            }
        });

        vehiculoTM=new VehiculoTableModel();
        jTable1.setModel(vehiculoTM);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener(){public void valueChanged(ListSelectionEvent lse){
            int fila=jTable1.getSelectedRow();
            if(fila>=0){
                mostrarMatricula((String)jTable1.getValueAt(fila, 0));
                mostrarTipo((Integer)jTable1.getValueAt(fila, 1)==0?"TURISMO":"FURGONETA");
                mostrarGrupo((String)jTable1.getValueAt(fila, 2));
                mostrarPlazas((Integer)jTable1.getValueAt(fila, 3));
                mostrarCapacidad((Float)jTable1.getValueAt(fila, 4));
                mostrarPrecioAlquiler((Float)jTable1.getValueAt(fila, 5));
            }
        }
    });

    labelOrden.setText("ORDEN DEL LISTADO");

    buttonGroup1.add(radioBotonMatricula);
    radioBotonMatricula.setSelected(true);
    radioBotonMatricula.setText("MATRICULA");
    radioBotonMatricula.setActionCommand("MATRICULA");
    radioBotonMatricula.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            radioBotonMatriculaActionPerformed(evt);
        }
    });

    buttonGroup1.add(radioBotonPrecioAlquiler);
    radioBotonPrecioAlquiler.setText("PRECIO ALQUILER");
    radioBotonPrecioAlquiler.setActionCommand("PRECIO ALQUILER");
    radioBotonPrecioAlquiler.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            radioBotonPrecioAlquilerActionPerformed(evt);
        }
    });

    labelFiltrarPorGrupo.setText("FILTRAR POR GRUPO");

    labelFiltrarPorTipo.setText("FILTRAR POR TIPO");

    comboBoxFiltrarGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "A", "B", "C" }));
    comboBoxFiltrarGrupo.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            comboBoxFiltrarGrupoActionPerformed(evt);
        }
    });

    comboBoxFiltrarTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TURISMO", "FURGONETA" }));
    comboBoxFiltrarTipo.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            comboBoxFiltrarTipoActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(172, 172, 172)
                    .addComponent(botonListar))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(labelOrden)
                            .addGap(76, 76, 76)
                            .addComponent(labelFiltrarPorGrupo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comboBoxFiltrarGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(labelFiltrarPorTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBoxFiltrarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(radioBotonMatricula)
                            .addGap(26, 26, 26)
                            .addComponent(radioBotonPrecioAlquiler)))))
            .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(31, 31, 31)
            .addComponent(botonListar)
            .addGap(29, 29, 29)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(61, 61, 61)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelOrden)
                .addComponent(labelFiltrarPorGrupo)
                .addComponent(labelFiltrarPorTipo)
                .addComponent(comboBoxFiltrarGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(comboBoxFiltrarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(61, 61, 61)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(radioBotonMatricula)
                .addComponent(radioBotonPrecioAlquiler))
            .addContainerGap(222, Short.MAX_VALUE))
    );

    menuArchivo.setText("Archivo");

    menuAbrir.setText("Abrir");
    menuAbrir.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuAbrirActionPerformed(evt);
        }
    });
    menuArchivo.add(menuAbrir);

    menuGuardar.setText("Guardar");
    menuGuardar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuGuardarActionPerformed(evt);
        }
    });
    menuArchivo.add(menuGuardar);

    jMenuBar1.add(menuArchivo);

    menuVehiculo.setText("Vehículo");

    menuNuevo.setText("Nuevo");
    menuNuevo.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuNuevoActionPerformed(evt);
        }
    });
    menuVehiculo.add(menuNuevo);

    menuBuscar.setText("Buscar");
    menuBuscar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuBuscarActionPerformed(evt);
        }
    });
    menuVehiculo.add(menuBuscar);

    jMenuBar1.add(menuVehiculo);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(42, 42, 42)
            .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(58, 58, 58))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxGrupoActionPerformed

    private void menuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbrirActionPerformed
        if(selectorFicheros.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            controlador.cargarVehiculo();
        }
    }//GEN-LAST:event_menuAbrirActionPerformed

    private void comboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTipoActionPerformed
        if(this.comboBoxTipo.getSelectedItem()=="TURISMO"){
            this.labelPlazas.setVisible(true);
            this.spinnerPlazas.setVisible(true);
            this.labelCapacidad.setVisible(false);
            this.formattedTextFieldCapacidad.setVisible(false);
        }else {
            this.labelPlazas.setVisible(false);
            this.spinnerPlazas.setVisible(false);
            this.labelCapacidad.setVisible(true);
            this.formattedTextFieldCapacidad.setVisible(true);
        }
    }//GEN-LAST:event_comboBoxTipoActionPerformed

    private void menuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNuevoActionPerformed
        
        if(dialogoVehiculo.mostrar()==DialogoVehiculo.ACEPTAR){
            mostrarMatricula(dialogoVehiculo.getMatricula());
            mostrarTipo(dialogoVehiculo.getTipo());
            mostrarGrupo(dialogoVehiculo.getGrupo());
            mostrarPlazas(dialogoVehiculo.getPlazas());
            mostrarCapacidad(dialogoVehiculo.getCapacidad());           
            try {
                controlador.crearVehiculo();
            } catch (MatriculaException ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_menuNuevoActionPerformed

    private void menuBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscarActionPerformed
        String matricula=JOptionPane.showInputDialog(this, "Matricula a buscar");
        if(matricula!=null){
            limpiarCampos();
            mostrarMatricula(matricula);
            controlador.buscarVehiculo();
        }
    }//GEN-LAST:event_menuBuscarActionPerformed

    private void menuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGuardarActionPerformed
        if(selectorFicheros.showSaveDialog(this)==JFileChooser.APPROVE_OPTION){
            controlador.guardarVehiculo();
        }
    }//GEN-LAST:event_menuGuardarActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        if(!getMatricula().isBlank()){
            controlador.eliminarVehiculo();
        }
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        controlador.modificarVehiculo();
    }//GEN-LAST:event_botonModificarActionPerformed

    private void botonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListarActionPerformed
        controlador.listarVehiculo();
    }//GEN-LAST:event_botonListarActionPerformed

    private void comboBoxFiltrarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxFiltrarGrupoActionPerformed
        controlador.listarVehiculo();
    }//GEN-LAST:event_comboBoxFiltrarGrupoActionPerformed

    private void comboBoxFiltrarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxFiltrarTipoActionPerformed
        controlador.listarVehiculo();
    }//GEN-LAST:event_comboBoxFiltrarTipoActionPerformed

    private void botonBaratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBaratoActionPerformed
        controlador.getVehiculosMasBarato();
    }//GEN-LAST:event_botonBaratoActionPerformed

    private void botonCaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCaroActionPerformed
        controlador.getVehiculosMasCaro();
    }//GEN-LAST:event_botonCaroActionPerformed

    private void radioBotonMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBotonMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBotonMatriculaActionPerformed

    private void radioBotonPrecioAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBotonPrecioAlquilerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBotonPrecioAlquilerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBarato;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonCaro;
    private javax.swing.JButton botonListar;
    private javax.swing.JButton botonModificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboBoxFiltrarGrupo;
    private javax.swing.JComboBox<String> comboBoxFiltrarTipo;
    private javax.swing.JComboBox<String> comboBoxGrupo;
    private javax.swing.JComboBox<String> comboBoxTipo;
    private javax.swing.JFormattedTextField formatedTextFieldPrecioAlquiler;
    private javax.swing.JFormattedTextField formattedTextFieldCapacidad;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private VehiculoTableModel vehiculoTM;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelCapacidad;
    private javax.swing.JLabel labelFiltrarPorGrupo;
    private javax.swing.JLabel labelFiltrarPorTipo;
    private javax.swing.JLabel labelGrupo;
    private javax.swing.JLabel labelMatricula;
    private javax.swing.JLabel labelOrden;
    private javax.swing.JLabel labelPlazas;
    private javax.swing.JLabel labelPrecioDia;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JMenuItem menuAbrir;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem menuBuscar;
    private javax.swing.JMenuItem menuGuardar;
    private javax.swing.JMenuItem menuNuevo;
    private javax.swing.JMenu menuVehiculo;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JRadioButton radioBotonMatricula;
    private javax.swing.JRadioButton radioBotonPrecioAlquiler;
    private javax.swing.JFileChooser selectorFicheros;
    private javax.swing.JSpinner spinnerPlazas;
    private javax.swing.JTextField textFieldMatricula;
    // End of variables declaration//GEN-END:variables
}
