/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controlador;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import modelo.DaoException;
import modelo.MatriculaException;
import modelo.Vehiculo;

/**
 *
 * @author marcos.fergar
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotonesListado = new javax.swing.ButtonGroup();
        selectorFicheros = new javax.swing.JFileChooser();
        datosVehiculos = new javax.swing.JPanel();
        labelMatricula = new javax.swing.JLabel();
        labelGrupo = new javax.swing.JLabel();
        labelTipo = new javax.swing.JLabel();
        labelPlazas = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        comboGrupo = new javax.swing.JComboBox<>();
        comboTipo = new javax.swing.JComboBox<>();
        textMatricula = new javax.swing.JTextField();
        spinnerPlazas = new javax.swing.JSpinner();
        formatedPrecio = new javax.swing.JFormattedTextField();
        botonBorrar = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        otrasOperaciones = new javax.swing.JPanel();
        botonVehiculoBarato = new javax.swing.JButton();
        botonVehiculoCaro = new javax.swing.JButton();
        labelCapacidad = new javax.swing.JLabel();
        formatedCapacidad = new javax.swing.JFormattedTextField();
        listadoVehiculos = new javax.swing.JPanel();
        botonVehiculos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVehiculos = new javax.swing.JTable();
        labelOrdenListado = new javax.swing.JLabel();
        botonMatricula = new javax.swing.JRadioButton();
        botonPrecio = new javax.swing.JRadioButton();
        labelFiltroGRupo = new javax.swing.JLabel();
        comboFiltroGrupo = new javax.swing.JComboBox<>();
        labelFiltroTipo = new javax.swing.JLabel();
        comboFiltroTipo = new javax.swing.JComboBox<>();
        menus = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuAbrir = new javax.swing.JMenuItem();
        menuGuardar = new javax.swing.JMenuItem();
        menuVehiculo = new javax.swing.JMenu();
        menuNuevo = new javax.swing.JMenuItem();
        menuBuscar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        datosVehiculos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de vehiculo"));

        labelMatricula.setText("MATRICULA");

        labelGrupo.setText("TIPO");

        labelTipo.setText("GRUPO");

        labelPlazas.setText("PLAZAS");

        labelPrecio.setText("PRECIO POR DIA");

        comboGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));
        comboGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboGrupoActionPerformed(evt);
            }
        });

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Turismo", "Furgoneta" }));
        comboTipo.setEnabled(false);
        comboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoActionPerformed(evt);
            }
        });

        formatedPrecio.setValue(0.0f);
        formatedPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatedPrecioActionPerformed(evt);
            }
        });

        botonBorrar.setText("BORRAR");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        botonModificar.setText("MODIFICAR");
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        otrasOperaciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Otras operaciones"));

        botonVehiculoBarato.setText("MOSTRAR VEHICULO MAS BARATO");
        botonVehiculoBarato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVehiculoBaratoActionPerformed(evt);
            }
        });

        botonVehiculoCaro.setText("MOSTRAR VEHICULO MAS CARO");
        botonVehiculoCaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVehiculoCaroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout otrasOperacionesLayout = new javax.swing.GroupLayout(otrasOperaciones);
        otrasOperaciones.setLayout(otrasOperacionesLayout);
        otrasOperacionesLayout.setHorizontalGroup(
            otrasOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otrasOperacionesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(otrasOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonVehiculoBarato, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(botonVehiculoCaro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        otrasOperacionesLayout.setVerticalGroup(
            otrasOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otrasOperacionesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(botonVehiculoBarato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(botonVehiculoCaro)
                .addGap(15, 15, 15))
        );

        labelCapacidad.setText("Capacidad");

        formatedCapacidad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        formatedCapacidad.setValue(0.0f);
        formatedCapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatedCapacidadActionPerformed(evt);
            }
        });
        formatedCapacidad.setVisible(false);

        javax.swing.GroupLayout datosVehiculosLayout = new javax.swing.GroupLayout(datosVehiculos);
        datosVehiculos.setLayout(datosVehiculosLayout);
        datosVehiculosLayout.setHorizontalGroup(
            datosVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosVehiculosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(datosVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datosVehiculosLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(botonBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonModificar)
                        .addGap(41, 41, 41))
                    .addGroup(datosVehiculosLayout.createSequentialGroup()
                        .addGroup(datosVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(otrasOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(datosVehiculosLayout.createSequentialGroup()
                                .addComponent(labelTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(labelGrupo)
                                .addGap(12, 12, 12)
                                .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(datosVehiculosLayout.createSequentialGroup()
                                .addComponent(labelPlazas)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(datosVehiculosLayout.createSequentialGroup()
                        .addGroup(datosVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCapacidad)
                            .addGroup(datosVehiculosLayout.createSequentialGroup()
                                .addComponent(labelMatricula)
                                .addGap(16, 16, 16)
                                .addComponent(textMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(datosVehiculosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(datosVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosVehiculosLayout.createSequentialGroup()
                        .addComponent(labelPrecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formatedPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(datosVehiculosLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(datosVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(formatedCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        datosVehiculosLayout.setVerticalGroup(
            datosVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosVehiculosLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(datosVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMatricula)
                    .addComponent(textMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(datosVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGrupo)
                    .addComponent(labelTipo)
                    .addComponent(comboGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(datosVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPlazas)
                    .addComponent(spinnerPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(datosVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCapacidad)
                    .addComponent(formatedCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(datosVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrecio)
                    .addComponent(formatedPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(datosVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBorrar)
                    .addComponent(botonModificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(otrasOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listadoVehiculos.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de vehiculos"));

        botonVehiculos.setText("LISTAR VEHICULOS");
        botonVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVehiculosActionPerformed(evt);
            }
        });

        tableModelTM2=new VehiculoTableModel();
        tablaVehiculos.setModel(tableModelTM2);
        jScrollPane1.setViewportView(tablaVehiculos);
        tablaVehiculos.getSelectionModel().addListSelectionListener(new ListSelectionListener(){public void valueChanged(ListSelectionEvent lse){
            int fila=tablaVehiculos.getSelectedRow();
            if(fila>=0){
                mostrarMatricula((String)tablaVehiculos.getValueAt(fila, 0));
                mostrarTipo((Integer)tablaVehiculos.getValueAt(fila, 1)==0?"Turismo":"Furgoneta");
                mostrarGrupo((String)tablaVehiculos.getValueAt(fila, 2));
                mostrarPlazas((Integer)tablaVehiculos.getValueAt(fila, 3));
                mostrarCapacidad((Float)tablaVehiculos.getValueAt(fila, 4));
                mostrarPrecioAlquiler((Float)tablaVehiculos.getValueAt(fila, 5));
            }
        }
    });

    labelOrdenListado.setText("ORDEN DEL LISTADO");

    grupoBotonesListado.add(botonMatricula);
    botonMatricula.setSelected(true);
    botonMatricula.setActionCommand("MATRICULA");
    botonMatricula.setText("MATRICULA");
    botonMatricula.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            botonMatriculaActionPerformed(evt);
        }
    });

    grupoBotonesListado.add(botonPrecio);
    botonPrecio.setText("PRECIO ALQUILER");
    botonPrecio.setActionCommand("PRECIO ALQUILER");

    labelFiltroGRupo.setText("FILTRAR POR GRUPO");

    comboFiltroGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "A", "B", "C" }));
    comboFiltroGrupo.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            comboFiltroGrupoActionPerformed(evt);
        }
    });

    labelFiltroTipo.setText("FILTRAR POR TIPO");

    comboFiltroTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TURISMO", "FURGONETA", " " }));

    javax.swing.GroupLayout listadoVehiculosLayout = new javax.swing.GroupLayout(listadoVehiculos);
    listadoVehiculos.setLayout(listadoVehiculosLayout);
    listadoVehiculosLayout.setHorizontalGroup(
        listadoVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(listadoVehiculosLayout.createSequentialGroup()
            .addGroup(listadoVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listadoVehiculosLayout.createSequentialGroup()
                    .addGap(292, 292, 292)
                    .addComponent(botonVehiculos))
                .addGroup(listadoVehiculosLayout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(labelOrdenListado)
                    .addGap(110, 110, 110)
                    .addComponent(labelFiltroGRupo)
                    .addGap(18, 18, 18)
                    .addComponent(comboFiltroGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(35, 35, 35)
                    .addComponent(labelFiltroTipo)
                    .addGap(18, 18, 18)
                    .addComponent(comboFiltroTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(listadoVehiculosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(botonMatricula)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(botonPrecio))
                .addGroup(listadoVehiculosLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    listadoVehiculosLayout.setVerticalGroup(
        listadoVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(listadoVehiculosLayout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addComponent(botonVehiculos)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(12, 12, 12)
            .addGroup(listadoVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelOrdenListado)
                .addComponent(labelFiltroGRupo)
                .addComponent(comboFiltroGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(labelFiltroTipo)
                .addComponent(comboFiltroTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(listadoVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(botonMatricula)
                .addComponent(botonPrecio))
            .addContainerGap(14, Short.MAX_VALUE))
    );

    menuArchivo.setText("Archivo");

    menuAbrir.setText("Abrir");
    menuAbrir.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuAbrirActionPerformed(evt);
        }
    });
    menuArchivo.add(menuAbrir);

    menuGuardar.setText("Guardar");
    menuGuardar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuGuardarActionPerformed(evt);
        }
    });
    menuArchivo.add(menuGuardar);

    menus.add(menuArchivo);

    menuVehiculo.setText("Vehiculo");

    menuNuevo.setText("Nuevo");
    menuNuevo.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuNuevoActionPerformed(evt);
        }
    });
    menuVehiculo.add(menuNuevo);

    menuBuscar.setText("Buscar");
    menuBuscar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuBuscarActionPerformed(evt);
        }
    });
    menuVehiculo.add(menuBuscar);

    menus.add(menuVehiculo);

    setJMenuBar(menus);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(datosVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(listadoVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(listadoVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
        .addGroup(layout.createSequentialGroup()
            .addGap(78, 78, 78)
            .addComponent(datosVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formatedPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatedPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formatedPrecioActionPerformed

    private void formatedCapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatedCapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formatedCapacidadActionPerformed

    private void comboGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboGrupoActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        if(!getMatricula().isBlank()){
            controlador.eliminarVehiculo();
        }
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        controlador.modificarVehiculo();
    }//GEN-LAST:event_botonModificarActionPerformed

    private void menuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNuevoActionPerformed
        if(dialogo.mostrar()==DialogoVehiculo.ACEPTAR){
            mostrarMatricula(dialogo.getMatricula());
            mostrarTipo(dialogo.getTipo());
            mostrarGrupo(dialogo.getGrupo());
            mostrarPlazas(dialogo.getPlazas());
            mostrarCapacidad(dialogo.getCapacidad());           
            try {
                controlador.crearVehiculo();
            } catch (MatriculaException ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_menuNuevoActionPerformed

    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed
        if(this.comboTipo.getSelectedItem()=="Turismo"){
            this.labelPlazas.setVisible(true);
            this.spinnerPlazas.setVisible(true);
            this.labelCapacidad.setVisible(false);
            this.formatedCapacidad.setVisible(false);
        }else {
            this.labelPlazas.setVisible(false);
            this.spinnerPlazas.setVisible(false);
            this.labelCapacidad.setVisible(true);
            this.formatedCapacidad.setVisible(true);
        }                           
    }//GEN-LAST:event_comboTipoActionPerformed

    private void botonMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonMatriculaActionPerformed

    private void botonVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVehiculosActionPerformed
        controlador.listarVehiculo();
    }//GEN-LAST:event_botonVehiculosActionPerformed

    private void botonVehiculoBaratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVehiculoBaratoActionPerformed
        controlador.getVehiculosMasBarato();
    }//GEN-LAST:event_botonVehiculoBaratoActionPerformed

    private void menuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbrirActionPerformed
        if(selectorFicheros.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            controlador.cargarVehiculo();
        }
    }//GEN-LAST:event_menuAbrirActionPerformed

    private void menuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGuardarActionPerformed
        if(selectorFicheros.showSaveDialog(this)==JFileChooser.APPROVE_OPTION){
            try {
                controlador.guardarVehiculo();
            } catch (DaoException ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_menuGuardarActionPerformed

    private void menuBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscarActionPerformed
        String matricula=JOptionPane.showInputDialog(this, "Matricula a buscar");
        if(matricula!=null){
            limpiarCampos();
            mostrarMatricula(matricula);
            controlador.buscarVehiculo();
        }
    }//GEN-LAST:event_menuBuscarActionPerformed

    private void comboFiltroGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFiltroGrupoActionPerformed
                   
    }//GEN-LAST:event_comboFiltroGrupoActionPerformed

    private void botonVehiculoCaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVehiculoCaroActionPerformed
        controlador.getVehiculosMasCaro();
    }//GEN-LAST:event_botonVehiculoCaroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    
    public String getMatricula() {
        return this.textMatricula.getText();
    }
    
    public String getGrupo() {
        return this.comboGrupo.getSelectedItem().toString();
    }
    
    public String getTipo() {
        return this.comboTipo.getSelectedItem().toString();
    }
    
    public int getPlazas() {
        return (Integer) this.spinnerPlazas.getValue();
    }
    
    public float getCapacidad() {

        return Float.parseFloat(this.formatedCapacidad.getValue().toString());
    }
    
    public String getArchivo() {
        return this.selectorFicheros.getSelectedFile().getAbsolutePath();
    }
    
    public String getOrden() {
        return this.grupoBotonesListado.getSelection().getActionCommand();
    }

    public String getFiltroGrupo() {
        return this.comboFiltroGrupo.getSelectedItem().toString();
    }
    
    public String getFiltroTipo() {
        return this.comboFiltroTipo.getSelectedItem().toString();
    }
    
    public void mostrar() {
        setVisible(true);
    }

    public void mostrarMatricula(String matricula) {
        this.textMatricula.setText(matricula);
    }

    public void mostrarTipo(String tipo) {
        this.comboTipo.setSelectedItem(tipo);
    }

    public void mostrarGrupo(String grupo) {
        this.comboGrupo.setSelectedItem(grupo);
    }

    public void mostrarPlazas(int plazas) {
        this.spinnerPlazas.setValue(plazas);
    }

    public void mostrarCapacidad(float capacidad) {
        this.formatedCapacidad.setValue(capacidad);
    }

    public void mostrarPrecioAlquiler(float precio) {
        this.formatedPrecio.setText(Float.toString(precio));
    }
    
    public void listarVehiculos(List<Vehiculo> listado) {
        tableModelTM2.setListado(listado);
    }
    
    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this,mensaje);
    }
    
    public boolean solicitarConfirmacion() {

        int opcion = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea continuar?", "Confirmación", JOptionPane.YES_NO_OPTION);
        return opcion == JOptionPane.YES_OPTION;

    }
    
    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }
    
    public void limpiarCampos() {
        this.textMatricula.setText("");
        this.spinnerPlazas.setValue(0);
        this.formatedCapacidad.setText("");
        this.formatedPrecio.setText("");
    }

    public final static int SI = 0;
    private DialogoVehiculo dialogo = new DialogoVehiculo(this, true);
    private Controlador controlador;
    private VehiculoTableModel vehiculoTM;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrar;
    private javax.swing.JRadioButton botonMatricula;
    private javax.swing.JButton botonModificar;
    private javax.swing.JRadioButton botonPrecio;
    private javax.swing.JButton botonVehiculoBarato;
    private javax.swing.JButton botonVehiculoCaro;
    private javax.swing.JButton botonVehiculos;
    private javax.swing.JComboBox<String> comboFiltroGrupo;
    private javax.swing.JComboBox<String> comboFiltroTipo;
    private javax.swing.JComboBox<String> comboGrupo;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JPanel datosVehiculos;
    private javax.swing.JFormattedTextField formatedCapacidad;
    private javax.swing.JFormattedTextField formatedPrecio;
    private javax.swing.ButtonGroup grupoBotonesListado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCapacidad;
    private javax.swing.JLabel labelFiltroGRupo;
    private javax.swing.JLabel labelFiltroTipo;
    private javax.swing.JLabel labelGrupo;
    private javax.swing.JLabel labelMatricula;
    private javax.swing.JLabel labelOrdenListado;
    private javax.swing.JLabel labelPlazas;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JPanel listadoVehiculos;
    private javax.swing.JMenuItem menuAbrir;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem menuBuscar;
    private javax.swing.JMenuItem menuGuardar;
    private javax.swing.JMenuItem menuNuevo;
    private javax.swing.JMenu menuVehiculo;
    private javax.swing.JMenuBar menus;
    private javax.swing.JPanel otrasOperaciones;
    private javax.swing.JFileChooser selectorFicheros;
    private javax.swing.JSpinner spinnerPlazas;
    private VehiculoTableModel tableModelTM2;
    private javax.swing.JTable tablaVehiculos;
    private javax.swing.JTextField textMatricula;
    // End of variables declaration//GEN-END:variables
}
