/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorUsuarios;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author alvaro.gargon.4
 */
public class VentanaUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form VentanaUsuarios
     */
    public VentanaUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectorFicheros = new javax.swing.JFileChooser();
        jMenuItem1 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        editarTextField = new javax.swing.JTextField();
        buscarBoton = new javax.swing.JButton();
        añadirBoton = new javax.swing.JButton();
        modificarBoton = new javax.swing.JButton();
        eliminarBoton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        nombreLabel = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailTextField1 = new javax.swing.JTextField();
        rollLabel1 = new javax.swing.JLabel();
        rolComboBox = new javax.swing.JComboBox<>();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        botonListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuExportar = new javax.swing.JMenuItem();
        menuImportar = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JMenu();
        menuCrear = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenuItem();
        menuBorrar = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de usuarios");

        jToolBar1.setRollover(true);
        jToolBar1.add(editarTextField);

        buscarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/busqueda.png"))); // NOI18N
        buscarBoton.setFocusable(false);
        buscarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buscarBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buscarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBotonActionPerformed(evt);
            }
        });
        jToolBar1.add(buscarBoton);

        añadirBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/anadir-usuario.png"))); // NOI18N
        añadirBoton.setFocusable(false);
        añadirBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        añadirBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        añadirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirBotonActionPerformed(evt);
            }
        });
        jToolBar1.add(añadirBoton);

        modificarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar-usuario.png"))); // NOI18N
        modificarBoton.setFocusable(false);
        modificarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modificarBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        modificarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBotonActionPerformed(evt);
            }
        });
        jToolBar1.add(modificarBoton);

        eliminarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/borrar-usuario.png"))); // NOI18N
        eliminarBoton.setFocusable(false);
        eliminarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eliminarBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(eliminarBoton);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "USUARIO"));

        nombreLabel.setText("NOMBRE");

        emailLabel.setText("EMAIL");

        rollLabel1.setText("ROL");

        rolComboBox.setEditable(true);
        rolComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "REGISTRADO", "ADMINISTRADOR", " " }));
        rolComboBox.setEnabled(false);

        passwordLabel.setText("PASSWORD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nombreLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailLabel)
                            .addComponent(rollLabel1)
                            .addComponent(passwordLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordField)
                            .addComponent(emailTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(rolComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rollLabel1)
                    .addComponent(rolComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        botonListar.setText("LISTAR USUARIOS");
        botonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListarActionPerformed(evt);
            }
        });

        utm=new UsuarioTableModel();
        tablaUsuarios.setModel(utm);
        jScrollPane1.setViewportView(tablaUsuarios);

        menuArchivo.setText("Archivo");

        menuExportar.setText("Exportar");
        menuExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExportarActionPerformed(evt);
            }
        });
        menuArchivo.add(menuExportar);

        menuImportar.setText("Importar");
        menuImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuImportarActionPerformed(evt);
            }
        });
        menuArchivo.add(menuImportar);

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(menuSalir);

        jMenuBar1.add(menuArchivo);

        menuUsuario.setText("Usuario");

        menuCrear.setText("Crear");
        menuCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCrearActionPerformed(evt);
            }
        });
        menuUsuario.add(menuCrear);

        menuEditar.setText("Editar");
        menuEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarActionPerformed(evt);
            }
        });
        menuUsuario.add(menuEditar);

        menuBorrar.setText("Borrar");
        menuBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBorrarActionPerformed(evt);
            }
        });
        menuUsuario.add(menuBorrar);

        jMenuBar1.add(menuUsuario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(botonListar)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(botonListar)
                .addGap(87, 87, 87))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarActionPerformed
        String nombre = editarTextField.getText();
        mostrarNombre(nombre);
        controlador.buscar();
        this.dialogoUsuario.mostrarNombre(getNombre());
        this.dialogoUsuario.mostrarEmail(getEmail());
        this.dialogoUsuario.mostrarRol(getRol());
        if (!this.getEditar().isBlank() && dialogoUsuario.mostrarEditar() == DialogoUsuario.ACEPTAR) {
            this.mostrarEmail(dialogoUsuario.getEmail());
            this.mostrarPassword(dialogoUsuario.getPassword());
            controlador.editar();
            controlador.listar();
        }
    }//GEN-LAST:event_menuEditarActionPerformed

    private void botonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListarActionPerformed
        controlador.listar();
    }//GEN-LAST:event_botonListarActionPerformed

    private void buscarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBotonActionPerformed
        String nombre = editarTextField.getText();
        if (!nombre.isBlank()) {
            mostrarNombre(nombre);
            controlador.buscar();
        }
    }//GEN-LAST:event_buscarBotonActionPerformed

    private void añadirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirBotonActionPerformed
        if (this.dialogoUsuario.mostrarCrear() == DialogoUsuario.ACEPTAR) {
            this.nombreTextField.setText(dialogoUsuario.getNombre());
            this.passwordField.setText(dialogoUsuario.getPassword());
            this.emailTextField1.setText(dialogoUsuario.getEmail());
            this.rolComboBox.setSelectedItem(dialogoUsuario.getRol());
            controlador.crear();
        }
    }//GEN-LAST:event_añadirBotonActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearActionPerformed
        if (this.dialogoUsuario.mostrarCrear() == DialogoUsuario.ACEPTAR) {
            this.nombreTextField.setText(dialogoUsuario.getNombre());
            this.passwordField.setText(dialogoUsuario.getPassword());
            this.emailTextField1.setText(dialogoUsuario.getEmail());
            this.rolComboBox.setSelectedItem(dialogoUsuario.getRol());
            controlador.crear();
        }
    }//GEN-LAST:event_menuCrearActionPerformed

    private void modificarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBotonActionPerformed

    }//GEN-LAST:event_modificarBotonActionPerformed

    private void menuBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBorrarActionPerformed
        if (!this.getEditar().isBlank()) {
            controlador.borrar();
        }
    }//GEN-LAST:event_menuBorrarActionPerformed

    private void menuExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExportarActionPerformed
       if(selectorFicheros.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            controlador.exportar();
        }
    }//GEN-LAST:event_menuExportarActionPerformed

    private void menuImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuImportarActionPerformed
        if(selectorFicheros.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            controlador.importar();
        }
    }//GEN-LAST:event_menuImportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaUsuarios().setVisible(true);
            }
        });
    }

    public void setControlador(ControladorUsuarios controlador) {
        this.controlador = controlador;
    }

    public String getNombre() {
        return this.nombreTextField.getText();
    }

    public String getPassword() {
        return String.valueOf(this.passwordField.getPassword());
    }

    public String getEditar() {
        return this.editarTextField.getText();
    }

    public String getEmail() {
        return this.emailTextField1.getText();
    }

    public String getRol() {
        return this.rolComboBox.getSelectedItem().toString();
    }

    public String getArchivo() {
        return this.selectorFicheros.getSelectedFile().getAbsolutePath();
    }

    public void mostrarNombre(String nombre) {
        this.nombreTextField.setText(nombre);
    }

    public void mostrarPassword(String password) {
        this.passwordField.setText(password);
    }

    public void mostrarEmail(String email) {
        this.emailTextField1.setText(email);
    }

    public void mostrarRol(String rol) {
        this.rolComboBox.setSelectedItem(rol);
    }

    public void mostrarUsuarios(List<Usuario> listado) {
        utm.setUsuarios(listado);
    }

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    public boolean solicitarConfiramcion(){
        int opcion = JOptionPane.showConfirmDialog(this, 
            "¿Está seguro que desea continuar?", "Confirmación", JOptionPane.YES_NO_OPTION);
        return opcion == JOptionPane.YES_OPTION;
    }

    public void mostrar() {
        setVisible(true);
    }

    public void limpiarCampos() {
        this.nombreTextField.setText("");
        this.emailTextField1.setText("");
        this.editarTextField.setText("");
    }

    private ControladorUsuarios controlador;
    private DialogoUsuario dialogoUsuario = new DialogoUsuario(this, true);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadirBoton;
    private javax.swing.JButton botonListar;
    private javax.swing.JButton buscarBoton;
    private javax.swing.JTextField editarTextField;
    private javax.swing.JButton eliminarBoton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem menuBorrar;
    private javax.swing.JMenuItem menuCrear;
    private javax.swing.JMenuItem menuEditar;
    private javax.swing.JMenuItem menuExportar;
    private javax.swing.JMenuItem menuImportar;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JButton modificarBoton;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JComboBox<String> rolComboBox;
    private javax.swing.JLabel rollLabel1;
    private javax.swing.JFileChooser selectorFicheros;
    private UsuarioTableModel utm;
    private javax.swing.JTable tablaUsuarios;
    // End of variables declaration//GEN-END:variables

}
