package vista;

import controlador.Controlador;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import modelo.Empleado;

/**
 *
 * @author alvaro.gargon.4
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form VentanaSistemaNominas
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @return 
     */
    @SuppressWarnings("unchecked")
    public String getDni(){
        return dniTextField.getText();
    }
    
    public String getTipo(){
        return this.tipoComboBox.getSelectedItem().toString();
    }
    
    public String getNombre(){
        return this.nombreFieldText.getText();
    }
    
    public float getSalario(){
        return Float.parseFloat(this.formatedTextFieldSalario.getValue().toString());
    }
    
    public int getHoras(){
        return (Integer)this.horasSpinner.getValue();
    }
    
    public String getArchivo(){
        return this.selectorFicheros.getSelectedFile().getAbsolutePath();
    }
    
    public String getOrden(){
        return this.grupoBotones.getSelection().getActionCommand();
    }
    
     public void mostrarTipo(String tipo){
        this.tipoComboBox.setSelectedItem(tipo);
    }
    public void mostrarDni(String dni){
        this.dniTextField.setText(dni);
    }
    
    public void mostrarNombre(String nombre){
        this.nombreFieldText.setText(nombre);
    }
    
    public void mostrarSalario(float salario){
        this.formatedTextFieldSalario.setValue(salario);
    }
    
    public void mostrarHoras (int horas){
        this.horasSpinner.setValue(horas);
    }
    
    public void mostrarIngresos (float ingresos){
        this.ingresosTextField.setText(Float.toString(ingresos));
    }
    
    public void limpiarCampos(){
        this.dniTextField.setText("");
        this.nombreFieldText.setText("");
        this.formatedTextFieldSalario.setText("");
        this.horasSpinner.setValue(0);
        this.tipoComboBox.setSelectedItem(0);
        this.ingresosTextField.setText("");
    }
    
    public void mostrar(){
        setVisible(true);
    }
    
    public void listarEmpleados(List<Empleado> listado){
        tb.setListado(listado);
    }
    
    public boolean solicitarConfiramcion(){
        int opcion = JOptionPane.showConfirmDialog(this, 
            "¿Está seguro que desea continuar?", "Confirmación", JOptionPane.YES_NO_OPTION);
        return opcion == JOptionPane.YES_OPTION;
    }
    
    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }
    
    public void mostrarMensaje(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje);
    }
    
    private Controlador controlador;
    private DialogoEmpleado dialogo=new DialogoEmpleado(this,true);
    public final static int SI=0;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones = new javax.swing.ButtonGroup();
        selectorFicheros = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        labelDNI = new javax.swing.JLabel();
        dniTextField = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        nombreFieldText = new javax.swing.JTextField();
        labelTipo = new javax.swing.JLabel();
        tipoComboBox = new javax.swing.JComboBox<>();
        labelSalario = new javax.swing.JLabel();
        LabelIngresos = new javax.swing.JLabel();
        ingresosTextField = new javax.swing.JTextField();
        botonBorrar = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        formatedTextFieldSalario = new javax.swing.JFormattedTextField();
        labelHoras = new javax.swing.JLabel();
        horasSpinner = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        botonListarEmpleados = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        radioButtonDNI = new javax.swing.JRadioButton();
        radioButtonNombre = new javax.swing.JRadioButton();
        radioButtonIngresos = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuArchivo = new javax.swing.JMenu();
        Abrir = new javax.swing.JCheckBoxMenuItem();
        Guardar = new javax.swing.JCheckBoxMenuItem();
        MenuEmpleado = new javax.swing.JMenu();
        Nuevo = new javax.swing.JCheckBoxMenuItem();
        Buscar = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2), "Datos del empleado"));
        jPanel1.setForeground(new java.awt.Color(204, 255, 255));

        labelDNI.setText("DNI");

        dniTextField.setEditable(false);
        dniTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniTextFieldActionPerformed(evt);
            }
        });

        labelNombre.setText("NOMBRE");

        labelTipo.setText("TIPO");

        tipoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fijo", "Eventual", " " }));
        tipoComboBox.setEnabled(false);
        tipoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoComboBoxActionPerformed(evt);
            }
        });

        labelSalario.setText("SALARIO");

        LabelIngresos.setText("INGRESOS");

        botonBorrar.setBackground(new java.awt.Color(204, 255, 255));
        botonBorrar.setText("BORRAR");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        botonModificar.setBackground(new java.awt.Color(204, 255, 255));
        botonModificar.setText("MODIFICAR");
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        formatedTextFieldSalario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        formatedTextFieldSalario.setValue(0.0f);
        formatedTextFieldSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatedTextFieldSalarioActionPerformed(evt);
            }
        });

        labelHoras.setText("HORAS");
        labelHoras.setVisible(false);

        horasSpinner.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonBorrar)
                .addGap(18, 18, 18)
                .addComponent(botonModificar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombre)
                            .addComponent(labelTipo)
                            .addComponent(labelDNI))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dniTextField)
                            .addComponent(nombreFieldText)
                            .addComponent(tipoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelSalario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formatedTextFieldSalario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelIngresos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingresosTextField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(horasSpinner)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDNI)
                    .addComponent(dniTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNombre)
                    .addComponent(nombreFieldText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTipo)
                    .addComponent(tipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSalario)
                    .addComponent(formatedTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHoras)
                    .addComponent(horasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelIngresos)
                    .addComponent(ingresosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBorrar)
                    .addComponent(botonModificar))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2), "Listado de empleados"));

        botonListarEmpleados.setBackground(new java.awt.Color(204, 255, 255));
        botonListarEmpleados.setText("LISTAR EMPLEADOS");
        botonListarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListarEmpleadosActionPerformed(evt);
            }
        });

        jLabel1.setText("ORDEN DEL LISTADO");

        grupoBotones.add(radioButtonDNI);
        radioButtonDNI.setSelected(true);
        radioButtonDNI.setText("DNI");
        radioButtonDNI.setActionCommand("DNI");

        grupoBotones.add(radioButtonNombre);
        radioButtonNombre.setText("NOMBRE");
        radioButtonNombre.setActionCommand("Nombre");

        grupoBotones.add(radioButtonIngresos);
        radioButtonIngresos.setText("INGRESOS");
        radioButtonIngresos.setActionCommand("INGRESOS");

        tb=new EmpleadoTableModel();
        jTable1.setModel(tb);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener(){public void valueChanged(ListSelectionEvent lse){
            int fila=jTable1.getSelectedRow();
            if(fila>=0){
                mostrarDni((String)jTable1.getValueAt(fila, 0));
                mostrarNombre((String)jTable1.getValueAt(fila, 1));
                mostrarTipo((Integer)jTable1.getValueAt(fila, 3)==0?"Fijo":"Eventual");
                mostrarSalario((Float)jTable1.getValueAt(fila, 2));
                mostrarHoras((Integer)jTable1.getValueAt(fila, 3));
                mostrarIngresos((Float)jTable1.getValueAt(fila, 4));
            }
        }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(123, 123, 123)
                    .addComponent(botonListarEmpleados))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(31, 31, 31)
                            .addComponent(radioButtonDNI)
                            .addGap(18, 18, 18)
                            .addComponent(radioButtonNombre)
                            .addGap(18, 18, 18)
                            .addComponent(radioButtonIngresos)))))
            .addContainerGap(16, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addComponent(botonListarEmpleados)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(radioButtonDNI)
                .addComponent(radioButtonNombre)
                .addComponent(radioButtonIngresos))
            .addGap(36, 36, 36))
    );

    MenuArchivo.setText("Archivo");
    MenuArchivo.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            MenuArchivoActionPerformed(evt);
        }
    });

    Abrir.setSelected(true);
    Abrir.setText("Abrir...");
    Abrir.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            AbrirActionPerformed(evt);
        }
    });
    MenuArchivo.add(Abrir);

    Guardar.setSelected(true);
    Guardar.setText("Guardar...");
    Guardar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            GuardarActionPerformed(evt);
        }
    });
    MenuArchivo.add(Guardar);

    jMenuBar1.add(MenuArchivo);

    MenuEmpleado.setText("Empleado");

    Nuevo.setSelected(true);
    Nuevo.setText("Nuevo...");
    Nuevo.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            NuevoActionPerformed(evt);
        }
    });
    MenuEmpleado.add(Nuevo);

    Buscar.setSelected(true);
    Buscar.setText("Buscar...");
    Buscar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            BuscarActionPerformed(evt);
        }
    });
    MenuEmpleado.add(Buscar);

    jMenuBar1.add(MenuEmpleado);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(37, 37, 37)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(36, 36, 36)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(49, 49, 49))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(95, 95, 95)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(75, 75, 75)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(26, 26, 26))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dniTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniTextFieldActionPerformed

    private void MenuArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuArchivoActionPerformed

    private void tipoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoComboBoxActionPerformed
        if(tipoComboBox.getSelectedItem().equals("Fijo")){
            this.labelHoras.setVisible(false);
            this.horasSpinner.setVisible(false);
        }else {
            labelHoras.setVisible(true);
            horasSpinner.setVisible(true);
        }
    }//GEN-LAST:event_tipoComboBoxActionPerformed

    private void formatedTextFieldSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatedTextFieldSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formatedTextFieldSalarioActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        if(!getNombre().isBlank()){
            controlador.eliminarEmpleado();
        }
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        if(selectorFicheros.showSaveDialog(this)==JFileChooser.APPROVE_OPTION){
            controlador.guardarEmpleado();
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirActionPerformed
        if(selectorFicheros.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            controlador.cargarEmpleado();
        }
    }//GEN-LAST:event_AbrirActionPerformed

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        if(dialogo.mostrar()==DialogoEmpleado.ACEPTAR){
            mostrarDni(dialogo.getDni());
            mostrarNombre(dialogo.getNombre());
            mostrarTipo(dialogo.getTipo());
            mostrarSalario(dialogo.getSalario());
            mostrarHoras(dialogo.getHoras());
            controlador.crearEmpleado();
        }
    }//GEN-LAST:event_NuevoActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        String dni=JOptionPane.showInputDialog(this, "Dni a buscar");
        if(dni!=null){
            limpiarCampos();
            mostrarDni(dni);
            controlador.buscarEmpleado();
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void botonListarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListarEmpleadosActionPerformed
        controlador.listarEmpleados();
    }//GEN-LAST:event_botonListarEmpleadosActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        controlador.modificarEmpleado();
        
    }//GEN-LAST:event_botonModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem Abrir;
    private javax.swing.JCheckBoxMenuItem Buscar;
    private javax.swing.JCheckBoxMenuItem Guardar;
    private javax.swing.JLabel LabelIngresos;
    private javax.swing.JMenu MenuArchivo;
    private javax.swing.JMenu MenuEmpleado;
    private javax.swing.JCheckBoxMenuItem Nuevo;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonListarEmpleados;
    private javax.swing.JButton botonModificar;
    private javax.swing.JTextField dniTextField;
    private javax.swing.JFormattedTextField formatedTextFieldSalario;
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JSpinner horasSpinner;
    private javax.swing.JTextField ingresosTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    EmpleadoTableModel tb;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelDNI;
    private javax.swing.JLabel labelHoras;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelSalario;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JTextField nombreFieldText;
    private javax.swing.JRadioButton radioButtonDNI;
    private javax.swing.JRadioButton radioButtonIngresos;
    private javax.swing.JRadioButton radioButtonNombre;
    private javax.swing.JFileChooser selectorFicheros;
    private javax.swing.JComboBox<String> tipoComboBox;
    // End of variables declaration//GEN-END:variables
}
