/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.sauces.appud10.vista;

import es.sauces.appud10.controlador.Controlador;
import es.sauces.appud10.modelo.Cuenta;
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author ambrosio
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectorFicheros = new javax.swing.JFileChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        tfBuscar = new javax.swing.JTextField();
        bBuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pCuenta = new javax.swing.JPanel();
        lCodigo = new javax.swing.JLabel();
        lTitular = new javax.swing.JLabel();
        lSaldo = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        tfTitular = new javax.swing.JTextField();
        tfSaldo = new javax.swing.JTextField();
        pListado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        miAbrir = new javax.swing.JMenuItem();
        miGuardar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miSalir = new javax.swing.JMenuItem();
        mBanco = new javax.swing.JMenu();
        miAbrirCuenta = new javax.swing.JMenuItem();
        miOperarCuenta = new javax.swing.JMenuItem();
        miCancelarCuenta = new javax.swing.JMenuItem();

        selectorFicheros.setCurrentDirectory(new File("."));
        selectorFicheros.setFileFilter(new FileFilter(){
            public boolean accept(File f){
                String n=f.getName();
                boolean b=false;
                if(f.isDirectory() || n.endsWith(".csv"))
                b=true;
                return b;
            }
            public String getDescription(){
                return "Archivos (*.csv)";
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BANCO SAUCES"); // NOI18N

        jPanel2.setLayout(new java.awt.BorderLayout());

        tfBuscar.setToolTipText("");

        bBuscar.setText("BUSCAR"); // NOI18N
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCuenta(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(tfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bBuscar)
                .addGap(0, 298, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscar))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.NORTH);

        pCuenta.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuenta"));

        lCodigo.setText("CÓDIGO"); // NOI18N

        lTitular.setText("TITULAR"); // NOI18N

        lSaldo.setText("SALDO"); // NOI18N

        tfCodigo.setEditable(false);

        tfTitular.setEditable(false);

        tfSaldo.setEditable(false);

        javax.swing.GroupLayout pCuentaLayout = new javax.swing.GroupLayout(pCuenta);
        pCuenta.setLayout(pCuentaLayout);
        pCuentaLayout.setHorizontalGroup(
            pCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pCuentaLayout.createSequentialGroup()
                        .addComponent(lCodigo)
                        .addGap(18, 18, 18)
                        .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pCuentaLayout.createSequentialGroup()
                        .addGroup(pCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lTitular)
                            .addComponent(lSaldo))
                        .addGap(18, 18, 18)
                        .addGroup(pCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTitular)
                            .addComponent(tfSaldo))))
                .addContainerGap(302, Short.MAX_VALUE))
        );
        pCuentaLayout.setVerticalGroup(
            pCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pCuentaLayout.createSequentialGroup()
                        .addGroup(pCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lCodigo)
                            .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lTitular))
                    .addComponent(tfTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSaldo)
                    .addComponent(tfSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pListado.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de cuentas"));

        ctm=new CuentaTableModel();
        jTable1.setModel(ctm);
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent ev){
                int fila=jTable1.getSelectedRow();
                if(fila>=0){
                    tfCodigo.setText((String)jTable1.getValueAt(fila, 0));
                    tfTitular.setText((String)jTable1.getValueAt(fila, 1));
                    tfSaldo.setText(jTable1.getValueAt(fila, 2).toString());
                }
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout pListadoLayout = new javax.swing.GroupLayout(pListado);
        pListado.setLayout(pListadoLayout);
        pListadoLayout.setHorizontalGroup(
            pListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
            .addGroup(pListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pListadoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(18, Short.MAX_VALUE)))
        );
        pListadoLayout.setVerticalGroup(
            pListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
            .addGroup(pListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pListadoLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pListado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(pListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel1, java.awt.BorderLayout.CENTER);

        mArchivo.setText("Archivo"); // NOI18N

        miAbrir.setText("Importar..."); // NOI18N
        miAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miImportarActionPerformed(evt);
            }
        });
        mArchivo.add(miAbrir);

        miGuardar.setText("Exportar..."); // NOI18N
        miGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExportarActionPerformed(evt);
            }
        });
        mArchivo.add(miGuardar);
        mArchivo.add(jSeparator1);

        miSalir.setText("Salir"); // NOI18N
        miSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirActionPerformed(evt);
            }
        });
        mArchivo.add(miSalir);

        jMenuBar1.add(mArchivo);

        mBanco.setText("Banco"); // NOI18N

        miAbrirCuenta.setText("Abrir cuenta"); // NOI18N
        miAbrirCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAbrirCuentaActionPerformed(evt);
            }
        });
        mBanco.add(miAbrirCuenta);

        miOperarCuenta.setText("Operar con cuenta"); // NOI18N
        miOperarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOperarCuentaActionPerformed(evt);
            }
        });
        mBanco.add(miOperarCuenta);

        miCancelarCuenta.setText("Cancelar cuenta"); // NOI18N
        miCancelarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCancelarCuentaActionPerformed(evt);
            }
        });
        mBanco.add(miCancelarCuenta);

        jMenuBar1.add(mBanco);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAbrirCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAbrirCuentaActionPerformed
        if(this.dialogo.mostrar()==DialogoCuenta.ACEPTAR){
            tfCodigo.setText(dialogo.getCodigo());
            tfTitular.setText(dialogo.getTitular());
            tfSaldo.setText(Float.toString(dialogo.getSaldo()));
            controlador.abrirCuenta();
        }
    }//GEN-LAST:event_miAbrirCuentaActionPerformed

    private void miOperarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOperarCuentaActionPerformed
        if(!getCodigo().isBlank()){
        controlador.operarConCuenta();
        }
    }//GEN-LAST:event_miOperarCuentaActionPerformed

    private void miCancelarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCancelarCuentaActionPerformed
       if(!getCodigo().isBlank()){
        controlador.cancelarCuenta();
       }
    }//GEN-LAST:event_miCancelarCuentaActionPerformed

    private void miImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miImportarActionPerformed
        if(selectorFicheros.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            controlador.importarCuentas();
        }
    }//GEN-LAST:event_miImportarActionPerformed

    private void miExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExportarActionPerformed
         if(selectorFicheros.showSaveDialog(this)==JFileChooser.APPROVE_OPTION){
            controlador.exportarCuentas();
        }
    }//GEN-LAST:event_miExportarActionPerformed

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_miSalirActionPerformed

    private void buscarCuenta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCuenta
      String codigo=tfBuscar.getText();
      if(!codigo.isBlank()){
          mostrarCodigo(codigo);
          controlador.buscarCuenta();
      }
    }//GEN-LAST:event_buscarCuenta

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    public void limpiarCampos(){
        tfCodigo.setText("");
         tfTitular.setText("");
          tfSaldo.setText("");
    }
    
    public void mostrar(){
        this.setVisible(true);
    }

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }
    
    public String getOperacion(){
        Object[] possibleValues = { "INGRESAR", "REINTEGRAR"};

        Object selectedValue = JOptionPane.showInputDialog(this,
             "OPERACIÓN A REALIZAR", "OPERAR CON CUENTA",
             JOptionPane.INFORMATION_MESSAGE, null,
             possibleValues, possibleValues[0]);
        return (String)selectedValue;
    }
    
    public float getCantidad(){
        String entrada=JOptionPane.showInputDialog(this,"INTRODUZCA CANTIDAD");
        return entrada!=null?Float.parseFloat(entrada):0;
    }
    
    public void mostrarCodigo(String codigo){
        tfCodigo.setText(codigo);
    }
    
    public void mostrarTitular(String titular){
        tfTitular.setText(titular);
    }
    
    public void mostrarSaldo(float saldo){
        tfSaldo.setText(Float.toString(saldo));
    }
    
    public String getCodigo(){
        return tfCodigo.getText();
    }
    
    public String getTitular(){
        return tfTitular.getText();
    }
    
    public float getSaldo(){
        return Float.parseFloat(tfSaldo.getText());
    }
    
    public void mostrarMensaje(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje);
    }
    
    public void mostrarCuentas(List<Cuenta> listado){
        ctm.setCuentas(listado);
    }
    
    public String getArchivo(){
        return selectorFicheros.getSelectedFile().getAbsolutePath();
    }
    
    public void actualizarSaldoTabla(){
       ctm.setValueAt(Float.parseFloat(tfSaldo.getText()), jTable1.getSelectedRow(), 2);
       
       
    }
   
    public CuentaTableModel getCtm() {
        return ctm;
    }

    public void setCtm(CuentaTableModel ctm) {
        this.ctm = ctm;
    }
    
    private Controlador controlador;
    private DialogoCuenta dialogo=new DialogoCuenta(this,true);
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private CuentaTableModel ctm;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lCodigo;
    private javax.swing.JLabel lSaldo;
    private javax.swing.JLabel lTitular;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenu mBanco;
    private javax.swing.JMenuItem miAbrir;
    private javax.swing.JMenuItem miAbrirCuenta;
    private javax.swing.JMenuItem miCancelarCuenta;
    private javax.swing.JMenuItem miGuardar;
    private javax.swing.JMenuItem miOperarCuenta;
    private javax.swing.JMenuItem miSalir;
    private javax.swing.JPanel pCuenta;
    private javax.swing.JPanel pListado;
    private javax.swing.JFileChooser selectorFicheros;
    private javax.swing.JTextField tfBuscar;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfSaldo;
    private javax.swing.JTextField tfTitular;
    // End of variables declaration//GEN-END:variables
}
