/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.sauces.appbanco2025.vista;

/**
 *
 * @author usuario
 */
public class DialogoCuenta extends javax.swing.JDialog {

    /**
     * Creates new form DialogoCuenta
     */
    public DialogoCuenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCuenta = new javax.swing.JPanel();
        tfCodigoCuenta = new javax.swing.JTextField();
        tfSaldoCuenta = new javax.swing.JTextField();
        lCodigo = new javax.swing.JLabel();
        lSaldo = new javax.swing.JLabel();
        bIngresar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        lTitular = new javax.swing.JLabel();
        tfTitular = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cuenta");
        setResizable(false);

        panelCuenta.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la cuenta"));

        lCodigo.setText("CÓDIGO");

        lSaldo.setText("SALDO");

        bIngresar.setText("ACEPTAR");
        bIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIngresarActionPerformed(evt);
            }
        });

        bCancelar.setText("CANCELAR");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        lTitular.setText("DNI DEL TITULAR");

        tfTitular.setEditable(false);

        javax.swing.GroupLayout panelCuentaLayout = new javax.swing.GroupLayout(panelCuenta);
        panelCuenta.setLayout(panelCuentaLayout);
        panelCuentaLayout.setHorizontalGroup(
            panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCuentaLayout.createSequentialGroup()
                        .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lTitular)
                            .addComponent(lCodigo)
                            .addComponent(lSaldo))
                        .addGap(18, 18, 18)
                        .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfSaldoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCodigoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(panelCuentaLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(bIngresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bCancelar)
                        .addGap(82, 82, 82))))
        );
        panelCuentaLayout.setVerticalGroup(
            panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTitular)
                    .addComponent(tfTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCodigo)
                    .addComponent(tfCodigoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSaldo)
                    .addComponent(tfSaldoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bIngresar)
                    .addComponent(bCancelar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIngresarActionPerformed
         if(tfCodigoCuenta.getText().trim().length()!=0 && tfTitular.getText().trim().length()!=0 && this.tfSaldoCuenta.getText().trim().length()!=0){
            opcion=ACEPTAR;
            setVisible(false);
        }
    }//GEN-LAST:event_bIngresarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        opcion=CANCELAR;
            setVisible(false);
    }//GEN-LAST:event_bCancelarActionPerformed
public int mostrarCrear(){
        opcion=CANCELAR;
        this.setTitle("Nueva Cuenta");
        this.tfCodigoCuenta.setEnabled(true);
        setVisible(true);
        return opcion;
    }
    
    public int mostrarEditar(){
        opcion=CANCELAR;
        this.setTitle("Editar Cuenta");
        this.tfCodigoCuenta.setEnabled(false);
        setVisible(true);
        return opcion;
    }
    
    public String getCodigo(){
        return this.tfCodigoCuenta.getText();
    }
    
    public String getTitular(){
        return this.tfTitular.getText();
    }
    
    public float getSaldo(){
        return Float.parseFloat(this.tfSaldoCuenta.getText());
    }
    
    public void mostrarCodigo(String codigo){
        this.tfCodigoCuenta.setText(codigo);
    }
    
    public void mostrarTitular(String titular){
        this.tfTitular.setText(titular);
    }
    
    public void mostrarSaldo(float saldo){
        this.tfSaldoCuenta.setText(Float.toString(saldo));
    }
    
    private int opcion;
    public static final int ACEPTAR=1;
    public static final int CANCELAR=0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bIngresar;
    private javax.swing.JLabel lCodigo;
    private javax.swing.JLabel lSaldo;
    private javax.swing.JLabel lTitular;
    private javax.swing.JPanel panelCuenta;
    private javax.swing.JTextField tfCodigoCuenta;
    private javax.swing.JTextField tfSaldoCuenta;
    private javax.swing.JTextField tfTitular;
    // End of variables declaration//GEN-END:variables
}
