
package es.sauces.appbanco2025.vista;



import es.sauces.appbanco2025.controlador.Controlador;
import es.sauces.appbanco2025.modelo.Movimiento;
import es.sauces.appbanco2025.modelo.TipoUsuario;
import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 * @author usuario
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        lUsuario = new javax.swing.JLabel();
        lPassword = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();
        bEntrar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        panelRegistrado = new javax.swing.JPanel();
        panelUsuario = new javax.swing.JPanel();
        lDni = new javax.swing.JLabel();
        lNombre = new javax.swing.JLabel();
        tfDni = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        bNuevoUsuario = new javax.swing.JButton();
        bEditarUsuario = new javax.swing.JButton();
        bBorrarUsuario = new javax.swing.JButton();
        lEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        lRol = new javax.swing.JLabel();
        cbRol = new javax.swing.JComboBox<>();
        panelCuentas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCuentas = new javax.swing.JList<>();
        bAbrirCuenta = new javax.swing.JButton();
        panelMovimientos = new javax.swing.JScrollPane();
        tablaMovimientos = new javax.swing.JTable();
        panelCuenta = new javax.swing.JPanel();
        tfCodigoCuenta = new javax.swing.JTextField();
        tfSaldoCuenta = new javax.swing.JTextField();
        lCodigo = new javax.swing.JLabel();
        lSaldo = new javax.swing.JLabel();
        bIngresar = new javax.swing.JButton();
        bReintegrar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuExamen = new javax.swing.JMenu();
        ejercicio1 = new javax.swing.JMenu();
        Ejercicio2 = new javax.swing.JMenu();
        ejercicio3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BANCO SAUCES");
        setResizable(false);

        panelLogin.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de acceso"));

        lUsuario.setText("USUARIO");

        lPassword.setText("PASSWORD");

        tfUsuario.setToolTipText("");

        pfPassword.setToolTipText("");

        bEntrar.setText("ENTRAR");
        bEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEntrarActionPerformed(evt);
            }
        });

        bSalir.setText("SALIR");
        bSalir.setEnabled(false);
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfUsuario)
                    .addComponent(pfPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addGap(72, 72, 72)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bEntrar)
                    .addComponent(bSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lUsuario)
                    .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bEntrar))
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lPassword)
                            .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(bSalir)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panelRegistrado.setVisible(false);
        pack();

        panelUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del usuario"));

        lDni.setText("DNI");

        lNombre.setText("NOMBRE");

        tfDni.setEditable(false);
        tfDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDniActionPerformed(evt);
            }
        });

        tfNombre.setEditable(false);

        bNuevoUsuario.setText("NUEVO");
        bNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuevoUsuarioActionPerformed(evt);
            }
        });

        bEditarUsuario.setText("EDITAR");
        bEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarUsuarioActionPerformed(evt);
            }
        });

        bBorrarUsuario.setText("BORRAR");
        bBorrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarUsuarioActionPerformed(evt);
            }
        });

        lEmail.setText("EMAIL");

        lRol.setText("ROL");

        cbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "REGISTRADO", "ADMINISTRADOR" }));
        cbRol.setEnabled(false);

        javax.swing.GroupLayout panelUsuarioLayout = new javax.swing.GroupLayout(panelUsuario);
        panelUsuario.setLayout(panelUsuarioLayout);
        panelUsuarioLayout.setHorizontalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lNombre)
                            .addComponent(lEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNombre)
                            .addComponent(tfEmail)))
                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUsuarioLayout.createSequentialGroup()
                                .addComponent(lDni)
                                .addGap(43, 43, 43)
                                .addComponent(tfDni, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelUsuarioLayout.createSequentialGroup()
                                .addComponent(bNuevoUsuario)
                                .addGap(18, 18, 18)
                                .addComponent(bEditarUsuario)
                                .addGap(18, 18, 18)
                                .addComponent(bBorrarUsuario))
                            .addGroup(panelUsuarioLayout.createSequentialGroup()
                                .addComponent(lRol, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelUsuarioLayout.setVerticalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDni)
                    .addComponent(tfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNombre)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEmail)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lRol)
                    .addComponent(cbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNuevoUsuario)
                    .addComponent(bEditarUsuario)
                    .addComponent(bBorrarUsuario))
                .addGap(18, 18, 18))
        );

        panelCuentas.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de cuentas"));

        listaCuentas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaCuentas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaCuentasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaCuentas);

        bAbrirCuenta.setText("ABRIR CUENTA");
        bAbrirCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAbrirCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCuentasLayout = new javax.swing.GroupLayout(panelCuentas);
        panelCuentas.setLayout(panelCuentasLayout);
        panelCuentasLayout.setHorizontalGroup(
            panelCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCuentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelCuentasLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(bAbrirCuenta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCuentasLayout.setVerticalGroup(
            panelCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuentasLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bAbrirCuenta))
        );

        panelMovimientos.setBorder(javax.swing.BorderFactory.createTitledBorder("Movimientos"));

        mtm=new MovimientoTableModel();
        tablaMovimientos.setModel(mtm);
        panelMovimientos.setViewportView(tablaMovimientos);
        if (tablaMovimientos.getColumnModel().getColumnCount() > 0) {
            tablaMovimientos.getColumnModel().getColumn(0).setResizable(false);
            tablaMovimientos.getColumnModel().getColumn(1).setResizable(false);
        }

        panelCuenta.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuenta"));

        tfCodigoCuenta.setEditable(false);

        tfSaldoCuenta.setEditable(false);
        tfSaldoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSaldoCuentaActionPerformed(evt);
            }
        });

        lCodigo.setText("CÓDIGO");

        lSaldo.setText("SALDO");

        bIngresar.setText("INGRESO");
        bIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIngresarActionPerformed(evt);
            }
        });

        bReintegrar.setText("REINTEGRO");
        bReintegrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReintegrarActionPerformed(evt);
            }
        });

        bCancelar.setText("CANCELAR CUENTA");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCuentaLayout = new javax.swing.GroupLayout(panelCuenta);
        panelCuenta.setLayout(panelCuentaLayout);
        panelCuentaLayout.setHorizontalGroup(
            panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelCuentaLayout.createSequentialGroup()
                            .addComponent(lCodigo)
                            .addGap(169, 169, 169))
                        .addGroup(panelCuentaLayout.createSequentialGroup()
                            .addComponent(tfCodigoCuenta)
                            .addGap(24, 24, 24)))
                    .addGroup(panelCuentaLayout.createSequentialGroup()
                        .addComponent(bIngresar)
                        .addGap(18, 18, 18)
                        .addComponent(bReintegrar)
                        .addGap(24, 24, 24)))
                .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bCancelar)
                    .addComponent(tfSaldoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSaldo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCuentaLayout.setVerticalGroup(
            panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCuentaLayout.createSequentialGroup()
                .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCodigo)
                    .addComponent(lSaldo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCodigoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSaldoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bIngresar)
                    .addComponent(bReintegrar)
                    .addComponent(bCancelar)))
        );

        javax.swing.GroupLayout panelRegistradoLayout = new javax.swing.GroupLayout(panelRegistrado);
        panelRegistrado.setLayout(panelRegistradoLayout);
        panelRegistradoLayout.setHorizontalGroup(
            panelRegistradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistradoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRegistradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCuenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMovimientos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                    .addGroup(panelRegistradoLayout.createSequentialGroup()
                        .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelRegistradoLayout.setVerticalGroup(
            panelRegistradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistradoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRegistradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        menuExamen.setText("Examen");

        ejercicio1.setText("Ejercicio1");
        menuExamen.add(ejercicio1);

        Ejercicio2.setText("Ejercicio2");
        menuExamen.add(Ejercicio2);

        ejercicio3.setText("Ejercicio3");
        menuExamen.add(ejercicio3);

        jMenuBar1.add(menuExamen);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelRegistrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelRegistrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaCuentasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaCuentasValueChanged
        mostrarCodigoCuenta(this.listaCuentas.getSelectedValue());
        controlador.buscarCuenta();
    }//GEN-LAST:event_listaCuentasValueChanged

    private void bBorrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarUsuarioActionPerformed
       if(!getDni().isBlank()){
           controlador.borrarUsuario();
       } 
    }//GEN-LAST:event_bBorrarUsuarioActionPerformed

    private void bIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIngresarActionPerformed
        if(!getCodigoCuenta().isBlank()){
            controlador.ingresar();
        }
    }//GEN-LAST:event_bIngresarActionPerformed

    private void bNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevoUsuarioActionPerformed
        if(this.dialogoUsuario.mostrarCrear()==DialogoUsuario.ACEPTAR){
            mostrarDni(dialogoUsuario.getDni());
            mostrarNombre(dialogoUsuario.getNombre());
            mostrarEmail(dialogoUsuario.getEmail());
            mostrarRol("REGISTRADO");
            controlador.crearUsuario();
        }
    }//GEN-LAST:event_bNuevoUsuarioActionPerformed

    private void bEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarUsuarioActionPerformed
        if(!getDni().isBlank()){
            dialogoUsuario.mostrarDni(getDni());
            dialogoUsuario.mostrarNombre(getNombre());
            dialogoUsuario.mostrarEmail(getEmail());
            if(dialogoUsuario.mostrarEditar()==DialogoUsuario.ACEPTAR){
                mostrarNombre(dialogoUsuario.getNombre());
                mostrarEmail(dialogoUsuario.getEmail());
                controlador.modificarUsuario();
            }
            
        }
    }//GEN-LAST:event_bEditarUsuarioActionPerformed

    private void bAbrirCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAbrirCuentaActionPerformed
        if(!getDni().isBlank()){
            dialogoCuenta.mostrarTitular(getDni());
            if(this.dialogoCuenta.mostrarCrear()==DialogoCuenta.ACEPTAR){
                mostrarCodigoCuenta(dialogoCuenta.getCodigo());
                mostrarSaldoCuenta(dialogoCuenta.getSaldo());
                controlador.abrirCuenta();
            }
        }
    }//GEN-LAST:event_bAbrirCuentaActionPerformed

    private void bReintegrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReintegrarActionPerformed
         if(!getCodigoCuenta().isBlank()){
            controlador.reintegrar();
        }
    }//GEN-LAST:event_bReintegrarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
         if(!getCodigoCuenta().isBlank()){
            controlador.cancelarCuenta();
        }
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEntrarActionPerformed
        controlador.hacerLogin();
    }//GEN-LAST:event_bEntrarActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        controlador.hacerLogout();
    }//GEN-LAST:event_bSalirActionPerformed

    private void tfSaldoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSaldoCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSaldoCuentaActionPerformed

    private void tfDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDniActionPerformed

    public boolean solicitarConfirmacion(){
        return JOptionPane.showConfirmDialog(this, "Seguro?")==JOptionPane.OK_OPTION;
    }
   
    public void setControlador(Controlador controlador){
        this.controlador=controlador;
        
    }
    
     public String getCodigoCuenta(){
        return tfCodigoCuenta.getText();
    }
      
    public String getDni(){
        return tfDni.getText();
    }
    
    public String getNombre(){
        return tfNombre.getText();
    }
    
    public String getEmail(){
        return tfEmail.getText();
    }
    
    public char[] getPassword(){
        return this.dialogoUsuario.getPassword();
    }
    
    
    public float getCantidad(){
        float cantidad=-1;
        String entrada;
                      
        entrada=JOptionPane.showInputDialog(this, "Introduzca cantidad");
        if(entrada!=null){
           
            try{
                cantidad=Float.parseFloat(entrada);
            }catch(NumberFormatException nfe){
                mostrarMensaje("Error en la entrada");
            }
           
        }
        return cantidad;
    }
    
    public String getDniU(){
        return this.tfUsuario.getText();
    }
    
    public String getPasswordU(){
        return String.valueOf(this.pfPassword.getPassword());
    }
    
    public float getSaldo(){
        return Float.parseFloat(this.tfSaldoCuenta.getText());
    }
    
    public void mostrarRol(String rol){
        this.cbRol.setSelectedItem(rol);
    }
    
    public void mostrarDni(String dni){
        tfDni.setText(dni);
        
    }
    
    public void mostrarEmail(String email){
        this.tfEmail.setText(email);
    }
    
    public void mostrarNombre(String nombre){
        tfNombre.setText(nombre);
    }
    
    public void mostrarCodigoCuenta(String codigo){
        this.tfCodigoCuenta.setText(codigo);
    }
    
    public void mostrarSaldoCuenta(float saldo){
        this.tfSaldoCuenta.setText(Float.toString(saldo));
    }
    
    public void mostrarMensaje(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje);
    }
    
    public void mostrarCuentas(String[] cuentas){
        this.listaCuentas.setListData(cuentas);
    }
    
    public void mostrarMovimientos(List<Movimiento> movimientos){
        this.mtm.setMovimientos(movimientos);
        
    }
    
    public void cambiarVista(TipoUsuario rol){
        if(rol==TipoUsuario.INVITADO){
            this.panelRegistrado.setVisible(false);
            this.bEntrar.setEnabled(true);
            this.bSalir.setEnabled(false);
        }
        else{
            this.panelRegistrado.setVisible(true);
            this.bEntrar.setEnabled(false);
            this.bSalir.setEnabled(true);
       }
        
       pack();
    }
   
  
    public void mostrar(){
        setVisible(true);
    
    }
    
    private MovimientoTableModel mtm;
    private DialogoCuenta dialogoCuenta=new DialogoCuenta(this,true);
    private DialogoUsuario dialogoUsuario=new DialogoUsuario(this,true);
    private Controlador controlador;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Ejercicio2;
    private javax.swing.JButton bAbrirCuenta;
    private javax.swing.JButton bBorrarUsuario;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bEditarUsuario;
    private javax.swing.JButton bEntrar;
    private javax.swing.JButton bIngresar;
    private javax.swing.JButton bNuevoUsuario;
    private javax.swing.JButton bReintegrar;
    private javax.swing.JButton bSalir;
    private javax.swing.JComboBox<String> cbRol;
    private javax.swing.JMenu ejercicio1;
    private javax.swing.JMenu ejercicio3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lCodigo;
    private javax.swing.JLabel lDni;
    private javax.swing.JLabel lEmail;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lPassword;
    private javax.swing.JLabel lRol;
    private javax.swing.JLabel lSaldo;
    private javax.swing.JLabel lUsuario;
    private javax.swing.JList<String> listaCuentas;
    private javax.swing.JMenu menuExamen;
    private javax.swing.JPanel panelCuenta;
    private javax.swing.JPanel panelCuentas;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JScrollPane panelMovimientos;
    private javax.swing.JPanel panelRegistrado;
    private javax.swing.JPanel panelUsuario;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTable tablaMovimientos;
    private javax.swing.JTextField tfCodigoCuenta;
    private javax.swing.JTextField tfDni;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfSaldoCuenta;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables

}
